apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-container
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: myapp
        image: registry.infrastructure.local/marchino/myapp:2
        ports:
        - containerPort: 3000
