apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: myapp
    image: registry.infrastructure.local/marchino/myapp
    ports:
    - name: nodejs-port
      containerPort: 3000
